// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: blob.proto

package protob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcClientID   string                 `protobuf:"bytes,1,opt,name=srcClientID,proto3" json:"srcClientID,omitempty"`
	DstClientID   string                 `protobuf:"bytes,2,opt,name=dstClientID,proto3" json:"dstClientID,omitempty"`
	GroupID       string                 `protobuf:"bytes,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	FileName      string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,9,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,10,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TaskId        string                 `protobuf:"bytes,11,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_blob_proto_rawDescGZIP(), []int{0}
}

func (x *Blob) GetSrcClientID() string {
	if x != nil {
		return x.SrcClientID
	}
	return ""
}

func (x *Blob) GetDstClientID() string {
	if x != nil {
		return x.DstClientID
	}
	return ""
}

func (x *Blob) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *Blob) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Blob) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Blob) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Blob) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Blob) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Blob) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *Blob) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_blob_proto protoreflect.FileDescriptor

const file_blob_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"blob.proto\x12\x04blob\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x02\n" +
	"\x04Blob\x12 \n" +
	"\vsrcClientID\x18\x01 \x01(\tR\vsrcClientID\x12 \n" +
	"\vdstClientID\x18\x02 \x01(\tR\vdstClientID\x12\x18\n" +
	"\agroupID\x18\x03 \x01(\tR\agroupID\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1f\n" +
	"\vchunk_index\x18\t \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\n" +
	" \x01(\x05R\vtotalChunks\x12\x17\n" +
	"\atask_id\x18\v \x01(\tR\x06taskIdB'Z%github.com/kannachi323/homelib/protobb\x06proto3"

var (
	file_blob_proto_rawDescOnce sync.Once
	file_blob_proto_rawDescData []byte
)

func file_blob_proto_rawDescGZIP() []byte {
	file_blob_proto_rawDescOnce.Do(func() {
		file_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blob_proto_rawDesc), len(file_blob_proto_rawDesc)))
	})
	return file_blob_proto_rawDescData
}

var file_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blob_proto_goTypes = []any{
	(*Blob)(nil),                  // 0: blob.Blob
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_blob_proto_depIdxs = []int32{
	1, // 0: blob.Blob.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blob_proto_init() }
func file_blob_proto_init() {
	if File_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blob_proto_rawDesc), len(file_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blob_proto_goTypes,
		DependencyIndexes: file_blob_proto_depIdxs,
		MessageInfos:      file_blob_proto_msgTypes,
	}.Build()
	File_blob_proto = out.File
	file_blob_proto_goTypes = nil
	file_blob_proto_depIdxs = nil
}
